Standardization
bitovi/react-numerics pull request #24
Opened 2022-09-08 15:11 UTC by WestonVincze

PR for standardization

2022-09-24 19:16 UTC, rlmcneary2 requested changes
Weston thanks for doing this, I do have some concerns. I don't know if you know all the answers or not. If you can let me know who I should talk to I'd appreciate it.

2022-09-24 19:16 UTC, rlmcneary2 commented on libs/react-numerics/tsconfig.json
> +  "include": ["@types", "src"],
I'm not familiar with all these options but do they affect the ability build and publish?

These defaults are set by NX during setup. Does this break any of the NX scripts (I wouldn't expect them to)?

I don't understand, why is `strict` false?

2022-09-24 19:16 UTC, rlmcneary2 commented on libs/react-numerics/README.md
> +## Need help or have questions?
If the docs aren't linked to by the package.json `homepage` then I think the first line in this help section should be a link to the documentation.

2022-09-24 19:16 UTC, rlmcneary2 commented on .nvmrc
> +16
Thank you!

2022-10-18 18:20 UTC, christopherjbaker commented
Closing for #27

2022-10-18 18:20 UTC, closed without merging